apps/api/urls.py
from django.urls import path

app_name = "api"

urlpatterns = [
    path("", name="api"),
]

apps/pages/urls.py
from django.urls import path
from .views import home_view

app_name = "pages"

urlpatterns = [
    path("", home_view, name="home"),
]

apps/project/urls.py
from django.urls import path
from apps.project.views import (
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectDetailView,
    ProjectListView,
)

app_name = "project"

urlpatterns = [
    path("", ProjectListView.as_view(), name="project_list"),
    path("create/", ProjectCreateView.as_view(), name="project_create"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="project_detail"),
    path("<int:pk>/update/", ProjectUpdateView.as_view(), name="project_update"),
    path("<int:pk>/delete/", ProjectDeleteView.as_view(), name="project_delete"),
]

apps/users/urls.py
from django.urls import path, include

app_name = "users"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
]

config/urls.py
"""
jbbaillet_dev URL Configuration
"""

from django.contrib import admin
from django.urls import path, include
from django.views import defaults as default_views
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        TemplateView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path('accounts/', include('allauth.urls')),
    path("pages", include("jbbaillet_dev.pages.urls")),
    path("users/", include("jbbaillet_dev.users.urls")),
    path("project/", include("project.urls")),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += (
        staticfiles_urlpatterns()
    )  # tell gunicorn where static files are in dev mode
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=str(settings.MEDIA_ROOT),
    )

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

apps/api/models.py
from django.db import models

# Create your models here.

apps/pages/models.py
from django.db import models

# Create your models here.

apps/project/models.py
from django.db import models
from django_extensions.db.fields import AutoSlugField
from django.utils.translation import gettext_lazy


# Create your models here.
class Project(models.Model):
    name = models.CharField(
        max_length=255, unique=True,
        verbose_name="project", default=""
    )
    slug = AutoSlugField(gettext_lazy("Slug"), populate_from=("name",))

    class Meta:
        verbose_name = "project"

    def __str__(self):
        """
        The string representation of this model is the slug.
        """
        return self.slug

apps/users/models.py
from django.db import models
from django.contrib.auth import models as auth_models


class User(auth_models.AbstractUser):
    """Utilisateur personnalisé pour l'application."""

apps/project/forms.py
from apps.project.models import Project
from django import forms


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = [
            'name',
        ]
        help_texts = {
            'name': 'Le nom de project',
        }

apps/pages/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "pages/home.html"


home_view = HomeView.as_view()

apps/project/views.py
from apps.project.models import Project
from apps.project.forms import ProjectForm
from django.views.generic import (CreateView, UpdateView,
                                  DeleteView, DetailView, ListView)

class ProjectCreateView(CreateView):
    model = Project
    template_name = "project/create_project.html"
    form_class = ProjectForm


class <built-in method title of str object at 0x7f44ccc4b8f0>UpdateView(UpdateView):
    model = Project
    template_name = "project/update_project.html"
    form_class = ProjectForm


class ProjectDeleteView(DeleteView):
    model = Project
    template_name = "project/delete_project.html"
    success_url = "/"  # Rediriger vers l'URL souhaitée après la suppression


class <built-in method title of str object at 0x7f44ccc4b8f0>DetailView(DetailView):
    model = <built-in method title of str object at 0x7f44ccc4b8f0>
    template_name = "project/detail_project.html"


class ProjectListView(ListView):
    model = Project
    template_name = "project/list_project.html"

templates/base.html
{% load webpack_loader static %}

<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>{% block title %}{% endblock title %}</title>
    
    {% block head_styles %}
      {% stylesheet_pack 'app' %}
    {% endblock head_styles %} 
    
    {% block head_scripts %}
      {% javascript_pack 'app' attrs='defer' %}
    {% endblock head_scripts %}
  </head>
  <body class="{% block body_classes %}position-relative min-vh-100{% endblock body_classes %}">
    {% block messages %}{% include 'partials/messages.html' %}{% endblock messages %}
    
    {% block navigation %}{% include 'partials/navigation.html' %}{% endblock navigation %}
    
    {% block header %}{# placer l'en-tête de la page ici #}{% endblock header %}
    
    {% block outer_content %}
        <main class="flex-grow-1 container">
          {% block content %}{# placer le contenu principal ici #}{% endblock content %}
        </main>
    {% endblock outer_content %}
    
    {% block footer %}{% include 'partials/footer.html' %}{% endblock footer %}
    
    {% block modal %}{# placer vos fenêtres modales ici #}{% endblock modal %}
    
    {% block bottom_scripts %}{# placer vos scripts de bas de page ici #}{% endblock bottom_scripts %}
  </body>
</html>

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home | jbbaillet_dev{% endblock title %}

{% block content %}
    <div class="container">
        <h1>Welcome to project jbbaillet_dev</h1>
    </div>
{% endblock content %}«

templates/partials/footer.html
<footer class="position-absolute bottom-0 w-100 bg-dark text-light p-3">
    <div class="container">
        &copy; 2023 Jean-Baptiste Baillet
    </div>
</footer>

templates/partials/messages.html
<div class="container">
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-dismissible {% if message.tags %}{{ message.tags }}{% endif %}">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  {% endif %}
</div>

templates/partials/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">jbbaillet_dev</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                {% url 'pages:home' as url %}
                <li class="nav-item">
                <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">Home{% if request.path == url %} <span class="visually-hidden">(current)</span>{% endif %}</a>
                </li>
                {% if not user.is_authenticated %}
                {% url 'users:login' as url %}
                <li class="nav-item">
                    <a class="nav-link {% if request.path == url %}active{% endif %}" {% if request.path == url %}aria-current="page"{% endif %} href="{{ url }}">Login {% if request.path == url %} <span class="visually-hidden">(current)</span>{% endif %}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/project/create_project.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3 class="mb-3">Ajouter <strong>project</strong></h3>
    <div class="row">
      <form method="post">
        {% csrf_token %}
        <input type="hidden" name="project" value="project">
        <input type="hidden" name="user_id" value="{{ request.user.id }}">
        <div class="form-group">
          {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </form>
    </div>
  </div>
  {% endblock %}

templates/project/delete_project.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3 class="mb-3">Supprimer <strong>project</strong></h3>
    <div class="row">
      <p>Êtes-vous sûr de vouloir supprimer cet élément ?</p>
      <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Supprimer</button>
        <a href="{% url '{{ cookiecutter.app_name }}_list' %}" class="btn btn-secondary">Annuler</a>
      </form>
    </div>
  </div>
  {% endblock %}

templates/project/detail_project.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3 class="mb-3">Détails de <strong>{{ cookiecutter.app_name }}</strong></h3>{% raw %}
    <div class="row">
      {% raw %}<p>Nom : {{ object.name }}</p>
      <p>Description : {{ object.description }}</p>
      <!-- Affichez d'autres attributs du modèle selon vos besoins -->
    </div>
  </div>
  {% endblock %}

templates/project/list_project.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3 class="mb-3">Liste des {{ cookiecutter.app_name_plural }}</h3>
    <div class="row">
      {% for {{ cookiecutter.app_name_singular }} in object_list %}
        <div class="card mb-3">
          <div class="card-body">
            <h5 class="card-title">{{ {{ cookiecutter.app_name_singular }}.name }}</h5>
            <p class="card-text">{{ {{ cookiecutter.app_name_singular }}.description }}</p>
            <!-- Affichez d'autres attributs du modèle selon vos besoins -->
          </div>
        </div>
        {% empty %}
      <p>Aucun {{ cookiecutter.app_name_singular }} trouvé.</p>
      {% endfor %}
    </div>
  </div>
  {% endblock %}

templates/project/update_project.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h3 class="mb-3">Modifier <strong>project</strong></h3>
    <div class="row">
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          {{ form.as_p }}
        </div>
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </form>
    </div>
  </div>
  {% endblock %}